# Generated by Django 5.2.1 on 2025-05-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pagerank_score', models.FloatField(default=0)),
                ('wikipedia_link', models.URLField(blank=True)),
                ('page_views', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='places', to='myapp.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='myapp.city')),
            ],
            options={
                'ordering': ['-pagerank_score'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('local_path', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.place')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('similarity_type', models.CharField(choices=[('structural', 'Structural similarity'), ('image_same_city', 'Image similarity (same city)'), ('image_diff_city', 'Image similarity (different city)')], max_length=20)),
                ('main_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_me', to='myapp.place')),
                ('similar_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_others', to='myapp.place')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('main_place', 'similar_place', 'similarity_type')},
            },
        ),
    ]
