# Generated by Django 5.2.1 on 2025-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='color_vector',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='colorbar_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
