# Generated by Django 5.2.1 on 2025-05-26 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_placeimage_color_vector_placeimage_colorbar_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('similarity_type', models.CharField(choices=[('structural', 'Structural similarity'), ('image_same_city', 'Image similarity (same city)'), ('image_diff_city', 'Image similarity (different city)')], max_length=20)),
                ('main_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_me', to='myapp.place')),
                ('similar_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_others', to='myapp.place')),
            ],
            options={
                'unique_together': {('main_place', 'similar_place', 'similarity_type')},
            },
        ),
    ]
